### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Di-Roll** [GoldenCrystal/NetUnicodeInfo#2]
I ask you to add the ability to localize symbol names.
In my case, I need Russian localization.

**Comment by GoldenCrystal** [comment]
Hello

To my knowledge, there exists no official and up-to-date localized version of the [Unicode Character Database](http://www.unicode.org/Public/UCD/latest/ucd/)
Considering this, I don't really see how I could provide localized character names in a reliable manner.

Could you provide some ideas on how you think this could be done ?

Thanks
