### ISSUE TITLE
Add ToString() or DebuggerDisplay on UnicodeBlock

### ISSUE THREAD

**Issue by KirillOsenkov** [GoldenCrystal/NetUnicodeInfo#3]
It would be awesome if UnicodeBlock had a ToString() (for debugger purposes). Something like this:

```
        /// <summary>
        /// Returns the name of this unicode block.
        /// </summary>
        public override string ToString()
        {
            return Name + " [" + CodePointRange.ToString() + "]";
        }
```

**Comment by GoldenCrystal** [comment]
Adding a few DebuggerDisplay attributes here and there would indeed be a good idea.
I first have to tweak things to make the build a bit smoother with AppVeyor, now that .NET Core is officially supported, but I'll do that just after.

**Comment by GoldenCrystal** [comment]
I've published an updated package.
Would you mind checking if everything is ok for you ?
Thanks

**Comment by KirillOsenkov** [comment]
Awesome, so much better! Thanks!
