### ISSUE TITLE
Add New character info

### ISSUE THREAD

**Issue by zizwiz** [GoldenCrystal/NetUnicodeInfo#5]
32FF was added recently for new Japanese era. Please add to the dll.

**Comment by GoldenCrystal** [comment]
Done: https://github.com/GoldenCrystal/NetUnicodeInfo/blob/3048572384726eef2eed58ebac25bcefab4be286/UnicodeInformation.Tests/UnicodeInfoTests.cs#L54
Unicode 12.1 will be available in version [2.4 of the package](https://www.nuget.org/packages/UnicodeInformation/2.4.0).
